services:
  backend:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    container_name: backend 
    ports:
      - "8000:80"
    volumes:
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - webapp
      
  frontend:
    image: nouha564/restaurant-frontend:latest
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4300:4200"
    networks:
      - webapp

  mysql:
    image: nouha564/restaurant-mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    networks:
      - webapp
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306
    ports:
      - "8080:80" 
    depends_on:
      - mysql
    networks:
      - webapp 

networks:
  webapp:
    driver: bridge

volumes:
  db_data:
  vendor_data: